### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by ArturoJoya** [martinezjas/project-website#9]
Now that the chunks of text are smaller, it may be beneficial to consider closing the outer bounds of the text such that it is more centered and reaches the borders of the frame a little less.

**Comment by martinezjas** [comment]
addressing with commit c2a49cfdc074043126267f163a2184cd2d70ab25, now checking if its OK

**Comment by martinezjas** [comment]
approved by @ArturoJoya and deployed
